server:
    port: 8080

spring:
    redis:
        host: 127.0.0.1
        port: 6379
        password:
        timeout: 10000
        pool:
          max-active: 200
          max-wait: -1
          max-idle: 8
          min-idle: 0
    datasource:
        name: test
        url: jdbc:mysql://192.168.226.128:3306/shirojwt?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password:
        # 使用Druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    # 404交给异常处理器处理
    mvc:
        throw-exception-if-no-handler-found: true
    # 404交给异常处理器处理
    resources:
        add-mappings: false

mybatis:
    # Mybatis配置Mapper路径
    mapper-locations: classpath:mapper/*.xml
    # Mybatis配置Model类对应
    type-aliases-package: com.wang.model.entity

pagehelper:
    # 为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值， 可以配置 pageNum,pageSize,count,pageSizeZero,reasonable
    params: count=countSql
    # 指定分页插件使用哪种方言
    helper-dialect: mysql
    # 分页合理化参数 pageNum<=0时会查询第一页 pageNum>pages(超过总数时) 会查询最后一页
    reasonable: 'true'
    # 支持通过 Mapper 接口参数来传递分页参数，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页
    support-methods-arguments: 'true'

mapper:
    # 通用Mapper的insertSelective和updateByPrimaryKeySelective中是否判断字符串类型!=''
    not-empty: true

logging:
    # Debug打印SQL
    level.com.wang.mapper: debug